#!/usr/bin/env bash
# platform_secrets.sh — put the platform's credentials in the cluster without
# ever putting them in git.
#
# The chain of custody:
#   .env (gitignored, this machine only)  ->  Kubernetes Secrets  ->  pods
#              ^ the ONLY copy
#
# .env is generated here on first run from the shape in .env.example, with
# passwords from `openssl rand`. It is then the source of truth: every run
# re-applies the SAME values, so re-deploying never invalidates the password
# already baked into Postgres's data directory. That is also why .env sits on
# cluster.sh's destroy DENY list — lose it and the PVCs become unreadable.
#
# Nothing here echoes a secret value. Printing one puts it in a session log, in
# a scrollback buffer, and eventually in a screenshot.
#
# Usage: scripts/platform_secrets.sh          (called by deploy_platform.sh)
#        ENV_FILE=... scripts/platform_secrets.sh   (tests point this elsewhere)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$REPO_ROOT/.env}"
KUBECTL=(kubectl --context "${KUBE_CONTEXT:-kind-mlops-taxi}")
APPLY="${APPLY:-1}"   # tests set APPLY=0 to exercise generation without a cluster

# --- 1. .env: generate once, then never overwrite -----------------------------
gen_secret() {
  # 32 hex chars: no quoting hazards in YAML, in psql, or in a URL.
  openssl rand -hex 16
}

gen_login_password() {
  # Same entropy, but for a credential a HUMAN-facing app validates. Metabase
  # rejects a password its complexity rule dislikes (`normal` = length plus at
  # least one digit; `strong` also wants a capital), and 32 random hex chars can
  # legitimately contain neither a digit nor an uppercase letter. The suffix
  # guarantees both without touching entropy, and stays inside the character set
  # the comment above promises: no quoting hazard in YAML, psql or a URL.
  printf '%sAa1\n' "$(openssl rand -hex 16)"
}

if [[ ! -f "$ENV_FILE" ]]; then
  echo "[secrets] no $ENV_FILE — generating one (values are random, and local to this machine)"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/platform_secrets.sh. NEVER commit this file.
# The passwords below are baked into the Postgres data directory and the MinIO
# volume: replacing them means destroying those volumes too.
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=$(gen_secret)
MLFLOW_TRACKING_URI=http://localhost:5000
MLFLOW_S3_ENDPOINT_URL=http://localhost:9000
MLFLOW_ARTIFACT_BUCKET=mlflow-artifacts
AWS_ACCESS_KEY_ID=mlflow
AWS_SECRET_ACCESS_KEY=$(gen_secret)
AWS_DEFAULT_REGION=us-east-1
POSTGRES_PASSWORD=$(gen_secret)
MLFLOW_DB_USER=mlflow
MLFLOW_DB_PASSWORD=$(gen_secret)
MARTS_DB_USER=marts
MARTS_DB_PASSWORD=$(gen_secret)
EOF
  chmod 600 "$ENV_FILE"
else
  echo "[secrets] using existing $ENV_FILE (not regenerated — the old passwords are inside the volumes)"
fi

# --- 1b. Additive keys: a NEW consumer arriving after .env was written --------
# M1-S4 taught this shape. `.env` is the source of truth precisely because its
# passwords are already baked into volumes — so it is never regenerated. But a
# milestone that adds a NEW database (marts here, Metabase's app-db at M1-S5)
# needs a NEW credential, and hard-failing "your .env is missing MARTS_DB_USER"
# would leave the operator hand-editing a secrets file: exactly the manual step
# the recipe exists to remove (MLOps charter).
#
# The distinction that makes this safe, and the reason this is a SEPARATE list
# from REQUIRED below: a value here is NOT yet inside any volume, so generating
# it is creation, not rotation. The moment a key's value has been written into a
# data directory it graduates to REQUIRED and must never be regenerated.
# Format: NAME=literal  (no value => generate a random secret; a *_ADMIN_PASSWORD
# key gets the login-safe generator instead — see gen_login_password).
ADDITIVE=(MARTS_DB_USER=marts MARTS_DB_PASSWORD=
          METABASE_DB_USER=metabase METABASE_DB_PASSWORD=
          METABASE_ADMIN_EMAIL=mlops@crosstown.local METABASE_ADMIN_PASSWORD=
          OPTUNA_DB_USER=optuna OPTUNA_DB_PASSWORD=
          FLYTE_DB_USER=flyte FLYTE_DB_PASSWORD=
          FLYTE_S3_ACCESS_KEY=flyte FLYTE_S3_SECRET_KEY=)
for spec in "${ADDITIVE[@]}"; do
  key="${spec%%=*}"; literal="${spec#*=}"
  if ! grep -q "^${key}=" "$ENV_FILE"; then
    if [[ -n "$literal" ]]; then
      value="$literal"
    elif [[ "$key" == *_ADMIN_PASSWORD ]]; then
      value="$(gen_login_password)"
    else
      value="$(gen_secret)"
    fi
    printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
    echo "[secrets] added $key to $ENV_FILE (new consumer; no existing volume holds it)"
  fi
done

# Read it without exporting the whole file into our environment's children.
# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a

# A missing key here means .env predates a new requirement — say which one
# instead of applying a Secret with an empty value that fails hours later.
REQUIRED=(MINIO_ROOT_USER MINIO_ROOT_PASSWORD AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
          POSTGRES_PASSWORD MLFLOW_DB_USER MLFLOW_DB_PASSWORD
          MARTS_DB_USER MARTS_DB_PASSWORD
          METABASE_DB_USER METABASE_DB_PASSWORD
          METABASE_ADMIN_EMAIL METABASE_ADMIN_PASSWORD
          OPTUNA_DB_USER OPTUNA_DB_PASSWORD
          FLYTE_DB_USER FLYTE_DB_PASSWORD
          FLYTE_S3_ACCESS_KEY FLYTE_S3_SECRET_KEY)
missing=()
for k in "${REQUIRED[@]}"; do
  [[ -n "${!k:-}" ]] || missing+=("$k")
done
if [[ ${#missing[@]} -gt 0 ]]; then
  echo "[secrets] FAIL: $ENV_FILE is missing values for: ${missing[*]}" >&2
  echo "[secrets] Add them (see .env.example) or delete .env to regenerate — but" >&2
  echo "[secrets] deleting it orphans any existing Postgres/MinIO volume." >&2
  exit 1
fi

# The MinIO chart names the user `mlflow` in infra/helm/minio/values.yaml. If
# .env disagrees, MLflow authenticates as a user that does not exist and the
# failure surfaces as an artifact 403 far downstream (gotcha #5's neighbourhood).
if [[ "$AWS_ACCESS_KEY_ID" != "mlflow" ]]; then
  echo "[secrets] FAIL: AWS_ACCESS_KEY_ID='$AWS_ACCESS_KEY_ID' but infra/helm/minio/values.yaml" >&2
  echo "[secrets]       creates the user 'mlflow'. They are twins — change both or neither." >&2
  exit 1
fi

if [[ "$APPLY" != "1" ]]; then
  echo "[secrets] APPLY=0 — .env validated, nothing applied to a cluster."
  exit 0
fi

# --- 2. Secrets: create-or-update, never "already exists" ---------------------
# `create --dry-run=client | apply` is the idempotent form: it converges an
# existing Secret to the .env values instead of failing (create) or silently
# leaving a stale password in place (create-if-absent).
apply_secret() {
  local ns="$1" name="$2"; shift 2
  local args=()
  for kv in "$@"; do args+=(--from-literal="$kv"); done
  "${KUBECTL[@]}" -n "$ns" create secret generic "$name" "${args[@]}" \
    --dry-run=client -o yaml | "${KUBECTL[@]}" apply -f - >/dev/null
  echo "[secrets] ok  $ns/$name"
}

# Secrets do not cross namespaces, so the mlflow-facing copies are deliberate
# duplicates of platform-side values, not drift.
apply_secret platform minio-root \
  "rootUser=$MINIO_ROOT_USER" "rootPassword=$MINIO_ROOT_PASSWORD"
apply_secret platform minio-mlflow-user \
  "secretKey=$AWS_SECRET_ACCESS_KEY"
apply_secret platform postgres-superuser \
  "password=$POSTGRES_PASSWORD"
apply_secret platform postgres-mlflow \
  "username=$MLFLOW_DB_USER" "password=$MLFLOW_DB_PASSWORD"
apply_secret mlflow mlflow-db \
  "username=$MLFLOW_DB_USER" "password=$MLFLOW_DB_PASSWORD"
apply_secret mlflow mlflow-s3 \
  "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
# Metabase's app-db credential (M1-S5). Its own namespace, because Secrets do not
# cross namespaces; the value is the same one postgres_databases.sh converges the
# role to, and .env is the single source of truth for both.
apply_secret metabase metabase-db \
  "username=$METABASE_DB_USER" "password=$METABASE_DB_PASSWORD"
# The marts credential Metabase queries the warehouse WITH — a second, distinct
# database user. Metabase connects to `marts` as `marts`, never as the superuser:
# a BI seat that can DROP the warehouse it reads is a BI seat one misclick from a
# restore. (`marts` owns the marts database, so it can still write; narrowing it
# to read-only is M2's job, when a second writer exists to narrow against.)
apply_secret metabase metabase-marts-db \
  "username=$MARTS_DB_USER" "password=$MARTS_DB_PASSWORD"
# Flyte's MinIO identity (M4-S2). Lives in `platform` because the MinIO chart's
# user Job reads it there — the same shape as minio-mlflow-user. Flyte's own
# copy of the value does NOT become a Secret here: the flyte-binary chart renders
# its storage credential itself out of values, so deploy_flyte.sh hands it over
# through a mode-600 temp overlay it deletes on exit (never on a command line,
# where `ps` would show it).
apply_secret platform minio-flyte-user \
  "secretKey=$FLYTE_S3_SECRET_KEY"
# The credential a TASK POD writes its outputs with (M4-S4). A separate Secret in
# a separate namespace from the one above because Secrets do not cross
# namespaces, and it holds ONLY the secret half: the endpoint and the access key
# id are not secret and live in the PodTemplate that consumes this
# (infra/manifests/flyte-task-podtemplate.yaml), where they can be read in a diff
# and are pinned as twins of infra/helm/flyte/values.yaml by a test.
#
# Why a task pod needs its own copy at all, which is not obvious: the flyte-binary
# config configures the SERVER's storage client, and the co-pilot Secret
# configures the co-pilot sidecar — but the Flyte 2 python runtime inside the task
# container builds its own `flyte.storage.S3` from the environment. With none set
# it falls through to the default AWS credential chain and tries to read an EC2
# instance-metadata endpoint that does not exist here, so a task RUNS and then
# dies uploading its outputs to `http://169.254.169.254/latest/api/token`.
apply_secret flyte flyte-task-storage \
  "FLYTE_AWS_SECRET_ACCESS_KEY=$FLYTE_S3_SECRET_KEY"

echo "[secrets] 10 secrets converged from $ENV_FILE (no values printed, by design)"
