#!/usr/bin/env bash
# platform_secrets.sh — put the platform's credentials in the cluster without
# ever putting them in git.
#
# The chain of custody:
#   .env (gitignored, this machine only)  ->  Kubernetes Secrets  ->  pods
#              ^ the ONLY copy
#
# .env is generated here on first run from the shape in .env.example, with
# passwords from `openssl rand`. It is then the source of truth: every run
# re-applies the SAME values, so re-deploying never invalidates the password
# already baked into Postgres's data directory. That is also why .env sits on
# cluster.sh's destroy DENY list — lose it and the PVCs become unreadable.
#
# Nothing here echoes a secret value. Printing one puts it in a session log, in
# a scrollback buffer, and eventually in a screenshot.
#
# Usage: scripts/platform_secrets.sh          (called by deploy_platform.sh)
#        ENV_FILE=... scripts/platform_secrets.sh   (tests point this elsewhere)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$REPO_ROOT/.env}"
KUBECTL=(kubectl --context "${KUBE_CONTEXT:-kind-mlops-taxi}")
APPLY="${APPLY:-1}"   # tests set APPLY=0 to exercise generation without a cluster

# --- 1. .env: generate once, then never overwrite -----------------------------
gen_secret() {
  # 32 hex chars: no quoting hazards in YAML, in psql, or in a URL.
  openssl rand -hex 16
}

if [[ ! -f "$ENV_FILE" ]]; then
  echo "[secrets] no $ENV_FILE — generating one (values are random, and local to this machine)"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/platform_secrets.sh. NEVER commit this file.
# The passwords below are baked into the Postgres data directory and the MinIO
# volume: replacing them means destroying those volumes too.
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=$(gen_secret)
MLFLOW_TRACKING_URI=http://localhost:5000
MLFLOW_S3_ENDPOINT_URL=http://localhost:9000
MLFLOW_ARTIFACT_BUCKET=mlflow-artifacts
AWS_ACCESS_KEY_ID=mlflow
AWS_SECRET_ACCESS_KEY=$(gen_secret)
AWS_DEFAULT_REGION=us-east-1
POSTGRES_PASSWORD=$(gen_secret)
MLFLOW_DB_USER=mlflow
MLFLOW_DB_PASSWORD=$(gen_secret)
EOF
  chmod 600 "$ENV_FILE"
else
  echo "[secrets] using existing $ENV_FILE (not regenerated — the old passwords are inside the volumes)"
fi

# Read it without exporting the whole file into our environment's children.
# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a

# A missing key here means .env predates a new requirement — say which one
# instead of applying a Secret with an empty value that fails hours later.
REQUIRED=(MINIO_ROOT_USER MINIO_ROOT_PASSWORD AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
          POSTGRES_PASSWORD MLFLOW_DB_USER MLFLOW_DB_PASSWORD)
missing=()
for k in "${REQUIRED[@]}"; do
  [[ -n "${!k:-}" ]] || missing+=("$k")
done
if [[ ${#missing[@]} -gt 0 ]]; then
  echo "[secrets] FAIL: $ENV_FILE is missing values for: ${missing[*]}" >&2
  echo "[secrets] Add them (see .env.example) or delete .env to regenerate — but" >&2
  echo "[secrets] deleting it orphans any existing Postgres/MinIO volume." >&2
  exit 1
fi

# The MinIO chart names the user `mlflow` in infra/helm/minio/values.yaml. If
# .env disagrees, MLflow authenticates as a user that does not exist and the
# failure surfaces as an artifact 403 far downstream (gotcha #5's neighbourhood).
if [[ "$AWS_ACCESS_KEY_ID" != "mlflow" ]]; then
  echo "[secrets] FAIL: AWS_ACCESS_KEY_ID='$AWS_ACCESS_KEY_ID' but infra/helm/minio/values.yaml" >&2
  echo "[secrets]       creates the user 'mlflow'. They are twins — change both or neither." >&2
  exit 1
fi

if [[ "$APPLY" != "1" ]]; then
  echo "[secrets] APPLY=0 — .env validated, nothing applied to a cluster."
  exit 0
fi

# --- 2. Secrets: create-or-update, never "already exists" ---------------------
# `create --dry-run=client | apply` is the idempotent form: it converges an
# existing Secret to the .env values instead of failing (create) or silently
# leaving a stale password in place (create-if-absent).
apply_secret() {
  local ns="$1" name="$2"; shift 2
  local args=()
  for kv in "$@"; do args+=(--from-literal="$kv"); done
  "${KUBECTL[@]}" -n "$ns" create secret generic "$name" "${args[@]}" \
    --dry-run=client -o yaml | "${KUBECTL[@]}" apply -f - >/dev/null
  echo "[secrets] ok  $ns/$name"
}

# Secrets do not cross namespaces, so the mlflow-facing copies are deliberate
# duplicates of platform-side values, not drift.
apply_secret platform minio-root \
  "rootUser=$MINIO_ROOT_USER" "rootPassword=$MINIO_ROOT_PASSWORD"
apply_secret platform minio-mlflow-user \
  "secretKey=$AWS_SECRET_ACCESS_KEY"
apply_secret platform postgres-superuser \
  "password=$POSTGRES_PASSWORD"
apply_secret platform postgres-mlflow \
  "username=$MLFLOW_DB_USER" "password=$MLFLOW_DB_PASSWORD"
apply_secret mlflow mlflow-db \
  "username=$MLFLOW_DB_USER" "password=$MLFLOW_DB_PASSWORD"
apply_secret mlflow mlflow-s3 \
  "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"

echo "[secrets] 6 secrets converged from $ENV_FILE (no values printed, by design)"
